version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    networks:
      - backend
  app:
    container_name: investment-app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGODB_URL=mongodb://mongo:27017/investment-app
      - CLIENT_URL=${CLIENT_URL}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
