version: "3"

services:
  investment-app:
    build: .
    image: investment-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/investment-app
    networks:
      - app-investment-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-investment-network

networks:
  app-investment-network:
    driver: bridge
